### ISSUE TITLE
Failed to Contact the OLS and other errors

### ISSUE THREAD

**Issue by thackmann** [PRIDE-Toolsuite/ols-dialog#14]
Like others, I receive the following error when trying to search the OLS:
 
![image](https://user-images.githubusercontent.com/34034632/169721622-c57f40ab-0fed-49a9-acee-ab9ee52d7f55.png)

Strangely, I am still able to retrieve some search results:
 
![image](https://user-images.githubusercontent.com/34034632/169721627-bffd3d6f-dafd-4892-843c-99a71150445d.png)

However, if I choose any search results, I receive an additional error:
 
![image](https://user-images.githubusercontent.com/34034632/169721635-d6a122e3-be9d-4e82-964c-4c81239e16cf.png)
Thank you for your insight into all the errors.

**Comment by kbarylyuk** [comment]
Hi folks,
same issue here. Trying to add Toxoplasma gondii in the species field, getting the same error dialogue. 
<img width="706" alt="image" src="https://user-images.githubusercontent.com/13316340/170789795-fb889bf5-2598-49c7-ba49-ff8ed0271868.png">
The term name search does not give any relevant species or TaxID result:
<img width="917" alt="image" src="https://user-images.githubusercontent.com/13316340/170790023-e0ea64b0-cfb5-4975-998d-2ccf0f940177.png">
The following is printed into the Terminal console at the same time:

```
2022-05-27 22:10:31,772 ERROR [AWT-EventQueue-0] u.a.e.p.t.o.d.t.AbstractTask [AbstractTask.java:294] uk.ac.ebi.pride.toolsuite.ols.dialog.task.impl.TermSearchTask@54ef7da4 failed on : java.lang.NullPointerException
java.lang.NullPointerException: null
	at uk.ac.ebi.pride.toolsuite.ols.dialog.task.impl.TermSearchTask.searchOnOntology(TermSearchTask.java:128)
	at uk.ac.ebi.pride.toolsuite.ols.dialog.task.impl.TermSearchTask.doInBackground(TermSearchTask.java:120)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```


The term ID search seems to be stuck and does not return anything at all:
<img width="917" alt="image" src="https://user-images.githubusercontent.com/13316340/170790359-15373022-09da-4c6a-9b58-801e1acb2b94.png">

The following is printed in the console at the same time:

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at uk.ac.ebi.pride.toolsuite.ols.dialog.OLSDialog.termIdSearchJButtonActionPerformed(OLSDialog.java:2746)
	at uk.ac.ebi.pride.toolsuite.ols.dialog.OLSDialog.access$3300(OLSDialog.java:46)
	at uk.ac.ebi.pride.toolsuite.ols.dialog.OLSDialog$24.actionPerformed(OLSDialog.java:1675)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:262)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3318)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.awt.Dialog.show(Dialog.java:1084)
	at java.awt.Component.show(Component.java:1671)
	at java.awt.Component.setVisible(Component.java:1623)
	at java.awt.Window.setVisible(Window.java:1014)
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at uk.ac.ebi.pride.toolsuite.ols.dialog.OLSDialog.<init>(OLSDialog.java:437)
	at uk.ac.ebi.pride.toolsuite.ols.dialog.OLSDialog.<init>(OLSDialog.java:236)
	at uk.ac.ebi.pride.gui.form.combo.model.AbstractMetadataComboSelectionModel$1.run(AbstractMetadataComboSelectionModel.java:107)
	at uk.ac.ebi.pride.toolsuite.gui.EDTUtils.invokeLater(EDTUtils.java:23)
	at uk.ac.ebi.pride.gui.form.combo.model.AbstractMetadataComboSelectionModel.setSelectedItem(AbstractMetadataComboSelectionModel.java:109)
	at javax.swing.JComboBox.setSelectedItem(JComboBox.java:578)
	at javax.swing.JComboBox.setSelectedIndex(JComboBox.java:624)
	at javax.swing.plaf.basic.BasicComboPopup$Handler.mouseReleased(BasicComboPopup.java:868)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3318)
	at com.apple.laf.AquaComboBoxPopup$1.processMouseEvent(AquaComboBoxPopup.java:157)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

I am running JRE 1.8 on an M1 Mac under MacOS Monterey:

`java -version`
```
java version "1.8.0_333"
Java(TM) SE Runtime Environment (build 1.8.0_333-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.333-b02, mixed mode)
```

This issue seems to be recurring. Is there an option to manually add species instead of using OLS?
Thank you!

**Comment by ypriverol** [comment]
Thanks for reporting the issue. I' reviewing the code.

**Comment by ypriverol** [comment]
@kbarylyuk @thackmann I have solve both issue. I will release a new version and also release a version of submission tool.

**Comment by kbarylyuk** [comment]
Hi @ypriverol 
Thank you for fixing this so promptly. How can I obtain the updated PRIDE Submission Tool with this bug fixed? Apologies if this question is trivial - I am not at all experienced with GitHub and Java to figure out how to get it from here, and the version that is available on the PRIDE web site is still the same 2.5.4 that has the bug.

**Comment by ypriverol** [comment]
We will release on Monday

**Comment by ypriverol** [comment]
@kbarylyuk the new version can be found here https://github.com/PRIDE-Archive/px-submission-tool/releases/download/2.5.5/px-submission-tool-2.5.5.zip

**Comment by kbarylyuk** [comment]
Thank you very much, @ypriverol! Everything has worked! Thank you for addressing the issue so promptly!

**Comment by SoumiaH** [comment]
Like others, I receive an error when trying to search the OLS with the old version.
Now I use the new version (**PRIDE Submission Tool 2.5.5**) but I still have the following issue when I want to valided this step :
![image](https://user-images.githubusercontent.com/106752131/171639697-72442967-8a87-44e0-a152-b308d2c86594.png)

Is there a new version that corrects this error?

**Comment by selvaebi** [comment]
Can you please check now ?? with the latest tool 2.5.6
