### ISSUE TITLE
No Connection to the OLS 

### ISSUE THREAD

**Issue by cdlawless** [PRIDE-Toolsuite/ols-dialog#18]
Hi All. 

I've recently run into issue of no connection to the OLS via the pride submission tool. I need to select another organism that is not in the list, but no connection can be made to the ontology look-up service. I've followed through all the similar (solved) issues and nothing corrects the issue. I have successfully uploaded before, using the same PC and same settings before. The only difference is that I am using version 2.7.1 of the submission tool.

The error I get is the pop-up dialogue to check my firewall and proxy settings. I know these are correct I have uploaded using the same settings with no issue previously. 

On the command prompt I get the following:
2023-10-05 16:07:43,072 ERROR [AWT-EventQueue-0] u.a.e.p.t.o.d.t.AbstractTask [AbstractTask.java:290] uk.ac.ebi.pride.toolsuite.ols.dialog.task.impl.GetOntologiesTask@4b4c6f2b failed on : org.springframework.web.client.RestClientException: Could not extract response: no suitable HttpMessageConverter found for response type [class uk.ac.ebi.pride.utilities.ols.web.service.model.OntologyQuery] and content type [text/html;charset=UTF-8]
org.springframework.web.client.RestClientException: Could not extract response: no suitable HttpMessageConverter found for response type [class uk.ac.ebi.pride.utilities.ols.web.service.model.OntologyQuery] and content type [text/html;charset=UTF-8]
	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:109)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:599)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:572)
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:280)
	at uk.ac.ebi.pride.utilities.ols.web.service.client.OLSClient.getOntologyQuery(OLSClient.java:417)
	at uk.ac.ebi.pride.utilities.ols.web.service.client.OLSClient.getOntologies(OLSClient.java:257)
	at uk.ac.ebi.pride.toolsuite.ols.dialog.task.impl.GetOntologiesTask.doInBackground(GetOntologiesTask.java:48)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

I noticed on the ols webpage OLS3 is no longer being updated and OLS4 is being tested. Is this related to this issue I'm having?

Any help greatly appreciated.

Kind Regards. 

Craig

**Comment by jblakele** [comment]
I am having the same issue since the new version 2.7.1

Any help would be appreciated. 

2023-10-05 15:16:20,567 ERROR [AWT-EventQueue-0] u.a.e.p.t.o.d.t.AbstractTask [AbstractTask.java:290] uk.ac.ebi.pride.toolsuite.ols.dialog.task.impl.TermSearchTask@72cda659 failed on : org.springframework.web.client.RestClientException: Could not extract response: no suitable HttpMessageConverter found for response type [class uk.ac.ebi.pride.utilities.ols.web.service.model.OntologyQuery] and content type [text/html;charset=UTF-8]
org.springframework.web.client.RestClientException: Could not extract response: no suitable HttpMessageConverter found for response type [class uk.ac.ebi.pride.utilities.ols.web.service.model.OntologyQuery] and content type [text/html;charset=UTF-8]
        at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:109)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:599)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:572)
        at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:280)
        at uk.ac.ebi.pride.utilities.ols.web.service.client.OLSClient.getOntologyQuery(OLSClient.java:417)
        at uk.ac.ebi.pride.utilities.ols.web.service.client.OLSClient.getOntologies(OLSClient.java:257)
        at uk.ac.ebi.pride.toolsuite.ols.dialog.task.impl.TermSearchTask.doInBackground(TermSearchTask.java:118)
        at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at javax.swing.SwingWorker.run(SwingWorker.java:334)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)

**Comment by ypriverol** [comment]
We will work on it and will be back to you as soon as possible.

**Comment by my-randa** [comment]
Same issue!
Any help would be appreciated.

**Comment by ypriverol** [comment]
solved.
